--DBS211 Chungon Tse 154928188 Lab3 28 Sep 2021
set serveroutput on
--1
SELECT * FROM PAYMENTS ORDER BY CUSTOMERNUMBER FETCH NEXT 10 ROWS ONLY;
--2
SELECT CONCAT(FIRSTNAME, LASTNAME) AS FULLNAME, EMAIL FROM EMPLOYEES WHERE OFFICECODE = 6;
SELECT FIRSTNAME || ' ' || LASTNAME AS FULLNAME, EMAIL FROM EMPLOYEES WHERE OFFICECODE = 6;
--3
SELECT CUSTOMERNUMBER, CUSTOMERNAME, CONTACTFIRSTNAME, CONTACTLASTNAME, PHONE FROM CUSTOMERS WHERE CITY = 'Paris';
--4
SELECT CUSTOMERNUMBER, CUSTOMERNAME, CONTACTLASTNAME || ', ' || 
CONTACTFIRSTNAME AS CONTACTFULLNAME, PHONE FROM CUSTOMERS WHERE COUNTRY = 'Canada';
--5
SELECT DISTINCT CUSTOMERNUMBER FROM PAYMENTS;
--6
SELECT CUSTOMERNUMBER, CHECKNUMBER, AMOUNT FROM PAYMENTS WHERE AMOUNT NOT BETWEEN 30000 AND 65000
ORDER BY AMOUNT DESC;
--7
SELECT * FROM ORDERS WHERE STATUS = 'Cancelled';
--8
SELECT PRODUCTCODE, PRODUCTNAME, BUYPRICE, MSRP, (MSRP - BUYPRICE) AS MARKUP,
 ROUND(((MSRP - BUYPRICE)/BUYPRICE * 100), 1) AS PERCMARKUP FROM PRODUCTS;
--9
SELECT * FROM PRODUCTS WHERE UPPER(PRODUCTNAME) LIKE '%CO%';
--10
SELECT * FROM CUSTOMERS WHERE UPPER(CONTACTFIRSTNAME) LIKE 'S%E%';
--11
INSERT INTO EMPLOYEES (EMPLOYEENUMBER, LASTNAME, FIRSTNAME, EXTENSION, EMAIL, OFFICECODE,
REPORTSTO, JOBTITLE)
VALUES (2017, 'Tse', 'Chungon', 'x999', 'cotse@myseneca.ca', 4, 1088, 'Cashier');
--12
SELECT * FROM EMPLOYEES WHERE EMPLOYEENUMBER = 2017;
--13
UPDATE EMPLOYEES SET JOBTITLE = 'Head Cashier' WHERE EMPLOYEENUMBER = 2017;
--14
INSERT INTO EMPLOYEES (EMPLOYEENUMBER, LASTNAME, FIRSTNAME, EXTENSION, EMAIL, OFFICECODE,
REPORTSTO, JOBTITLE)
VALUES (2018, 'Mo', 'Gerard', 'x969', 'gmo@myseneca.ca', 4, 2017, 'Cashier');
--15
DELETE FROM EMPLOYEES WHERE EMPLOYEENUMBER = 2017;
--16
DELETE FROM EMPLOYEES WHERE EMPLOYEENUMBER = 2018;
DELETE FROM EMPLOYEES WHERE EMPLOYEENUMBER = 2017;
--17
INSERT ALL
INTO EMPLOYEES VALUES (2017, 'Tse', 'Chungon', 'x999', 'cotse@myseneca.ca', 4, 1088, 'Cashier')
INTO EMPLOYEES VALUES (2018, 'Mo', 'Gerard', 'x969', 'gmo@myseneca.ca', 4, 1088, 'Cashier')
SELECT * FROM DUAL;
--18
DELETE FROM EMPLOYEES
WHERE EMPLOYEENUMBER IN (2017, 2018);
--19
INSERT INTO ORDERS
VALUES (10426,to_date('2021-09-17','yyyy-mm-dd'),to_date('2021-09-22','yyyy-mm-dd')
,to_date('2021-09-30','yyyy-mm-dd'),'In Process',NULL,282);
SELECT * FROM ORDERS WHERE ORDERNUMBER = 10426;
--20
INSERT INTO PRODUCTS (PRODUCTCODE, PRODUCTNAME, PRODUCTLINE, PRODUCTSCALE, PRODUCTVENDOR,
PRODUCTDESCRIPTION, QUANTITYINSTOCK, BUYPRICE, MSRP)
VALUES ('S111_111', '2020 Bugatti Veyron', 'Classic Cars', '1:12', 'Seneca Workshop',
'This replica was Seneca''s biggest hit in 2020.', 1000, 49.99, 89.99);
SELECT * FROM PRODUCTS WHERE PRODUCTCODE = 'S111_111';